secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    build:
      context: .
      args:
        VERSION: ${IMAGE_VERSION:-latest}
    hostname: ${HOSTNAME}
    volumes:
      - type: bind
        source: ${FVTT_USER_DATA}
        target: /data
    ports:
      - target: ${FVTT_TARGET_PORT:-30000}
        published: ${FVTT_PUB_PORT:-30000}
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json
